# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BL03U_MassSpectrumTool.ui'
#
# Created by: PyQt6 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BL03U_MassSpectrumTools(object):
    def setupUi(self, BL03U_MassSpectrumTools):
        BL03U_MassSpectrumTools.setObjectName("BL03U_MassSpectrumTools")
        BL03U_MassSpectrumTools.resize(312, 284)
        self.centralwidget = QtWidgets.QWidget(BL03U_MassSpectrumTools)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    border: 1px solid #cccccc; /* 边框颜色 */\n"
"    border-radius: 8px; /* 边框圆角 */\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: none; /* 移除边框 */\n"
"    border-radius: 8px; /* 适中的圆角 */\n"
"    padding: 10px 20px; /* 增加内边距，使按钮更加宽敞 */\n"
"    background-color: #007BFF; /* 深蓝色背景，更加醒目 */\n"
"    color: white; /* 字体颜色保持白色 */\n"
"    min-width: 120px; /* 增加最小宽度 */\n"
"    min-height: 20px; /* 增加最小高度 */\n"
"    font: bold 18px; /* 增加字体大小，使其更加突出 */\n"
"    transition: background-color 0.3s, transform 0.1s; /* 添加背景颜色和变形渐变效果 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2); /* 添加阴影，增加立体感 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* 鼠标悬停时的背景颜色更深 */\n"
"    transform: scale(1.05); /* 轻微放大按钮，增加互动感 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003d82; /* 按钮被按下时的背景颜色更深 */\n"
"    transform: scale(0.95); /* 轻微缩小按钮，模拟按下效果 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: none; /* 移除边框 */\n"
"    border-radius: 8px; /* 适中的圆角 */\n"
"    padding: 10px 20px; /* 增加内边距，使按钮更加宽敞 */\n"
"    background-color: #007BFF; /* 深蓝色背景，更加醒目 */\n"
"    color: white; /* 字体颜色保持白色 */\n"
"    min-width: 120px; /* 增加最小宽度 */\n"
"    min-height: 20px; /* 增加最小高度 */\n"
"    font: bold 18px; /* 增加字体大小，使其更加突出 */\n"
"    transition: background-color 0.3s, transform 0.1s; /* 添加背景颜色和变形渐变效果 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2); /* 添加阴影，增加立体感 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* 鼠标悬停时的背景颜色更深 */\n"
"    transform: scale(1.05); /* 轻微放大按钮，增加互动感 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003d82; /* 按钮被按下时的背景颜色更深 */\n"
"    transform: scale(0.95); /* 轻微缩小按钮，模拟按下效果 */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: none; /* 移除边框 */\n"
"    border-radius: 8px; /* 适中的圆角 */\n"
"    padding: 10px 20px; /* 增加内边距，使按钮更加宽敞 */\n"
"    background-color: #007BFF; /* 深蓝色背景，更加醒目 */\n"
"    color: white; /* 字体颜色保持白色 */\n"
"    min-width: 120px; /* 增加最小宽度 */\n"
"    min-height: 20px; /* 增加最小高度 */\n"
"    font: bold 18px; /* 增加字体大小，使其更加突出 */\n"
"    transition: background-color 0.3s, transform 0.1s; /* 添加背景颜色和变形渐变效果 */\n"
"    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2); /* 添加阴影，增加立体感 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* 鼠标悬停时的背景颜色更深 */\n"
"    transform: scale(1.05); /* 轻微放大按钮，增加互动感 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003d82; /* 按钮被按下时的背景颜色更深 */\n"
"    transform: scale(0.95); /* 轻微缩小按钮，模拟按下效果 */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        BL03U_MassSpectrumTools.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BL03U_MassSpectrumTools)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 312, 22))
        self.menubar.setObjectName("menubar")
        BL03U_MassSpectrumTools.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BL03U_MassSpectrumTools)
        self.statusbar.setObjectName("statusbar")
        BL03U_MassSpectrumTools.setStatusBar(self.statusbar)

        self.retranslateUi(BL03U_MassSpectrumTools)
        QtCore.QMetaObject.connectSlotsByName(BL03U_MassSpectrumTools)

    def retranslateUi(self, BL03U_MassSpectrumTools):
        _translate = QtCore.QCoreApplication.translate
        BL03U_MassSpectrumTools.setWindowTitle(_translate("BL03U_MassSpectrumTools", "MainWindow"))
        self.label.setText(_translate("BL03U_MassSpectrumTools", "燃烧站光电离质谱数据处理软件"))
        self.pushButton.setText(_translate("BL03U_MassSpectrumTools", "卡峰及质谱定标工具"))
        self.pushButton_2.setText(_translate("BL03U_MassSpectrumTools", "热解曲线及PIE曲线绘制"))
        self.pushButton_3.setText(_translate("BL03U_MassSpectrumTools", "PIE拟合工具"))
        self.pushButton_4.setText(_translate("BL03U_MassSpectrumTools", "退出"))
